version: '3.3'

services:  
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - /media/nimz/Library/RAHASAK/AirQuality/docker_mqtt/config:/mosquitto/config
      - /media/nimz/Library/RAHASAK/AirQuality/docker_mqtt/data:/mosquitto/data
      - /media/nimz/Library/RAHASAK/AirQuality/docker_mqtt/log:/mosquitto/log
